### PR TITLE
Fix to read auxiliaryFiles and publish for github install.

### PR DESCRIPTION
**Pull request by richtera**
Fix to read both auxiliaryFiles and files inside of each chunk when searching for map assets.

### CODE REVIEW

**Comment by richtera** [comment]
NOTE: I pushed the dist folder into this PR, so I can install the npm directly from github.

**Comment by richtera** [comment]
Somehow the checks are taking forever and don't show any errors. Not sure what I can do to help.
This PR is required to make the plugin work for the latest webpack as far as I can tell, because the map files are now in the auxiliaryFiles array and not in the main array.

**Comment by mskelton** [comment]
@richtera See https://github.com/thredup/rollbar-sourcemap-webpack-plugin/pull/327 which updates this plugin to webpack 5.

**Comment by richtera** [comment]
Perfect. Either merge is fine, thanks for the info.

**Comment by mskelton** [comment]
The other PR also updates the peer dependency range to allow webpack 5, so I would recommend closing this one in favor of #327.

**Comment by brandondoran** [comment]
@richtera thanks for the PR. I will be going with #327. I will merge that and publish a new version today.

**Comment by brandondoran** [comment]
@richtera #327 is merged and published as v3.2.0

**Pull request closed without merging**
