### PR TITLE
Support webpack 4 hooks API

### PR DESCRIPTION
**Pull request by ColinWhitmarsh**
Hello,

This PR supports the new `.hooks` API in webpack 4 https://webpack.js.org/api/plugins/. It should remove the warning `DepreciationWarning: Tappable.plugin is deprecated. Use new API on '.hooks'`. 

The PR is backwards compatible with the old `.plugin` API. If this is something you're interested in merging I'm happy to make whatever changes are necessary.

-Colin

### CODE REVIEW

**Comment by palnes** [comment]
Any updates on this?

**Comment by fraserxu** [comment]
Would love to see this get merged ❤️

**Comment by tmcdonnell87** [comment]
I was about to create this PR, until I saw it was done. @brandondoran, anything holding it up?

**Comment by brandondoran** [comment]
The PR is now merged and published to npm as v2.4.0! Thanks for submitting @ColinWhitmarsh 

@tmcdonnell87 @palnes @fraserxu sorry for the delay.

**Pull request merged**
